#!/usr/bin/env sh

# Version corregida para Windows/Git Bash

# Detectar Windows/MINGW de una manera más compatible

case "$(uname -s)" in
MINGW* | MSYS*) # Windows (Git Bash/MINGW)
npx --no -- commitlint --edit "$1" --verbose
;;
\*) # Unix/Linux u otros sistemas
npx --no -- commitlint --edit "$1" --verbose
;;
esac
